<?php

namespace AppBundle\Repository;

/**
 * QuizzesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizzesRepository extends \Doctrine\ORM\EntityRepository
{
}
